spring:
  application:
    name: stock-service

  config:
    import: ${SPRING_CONFIG_IMPORT}
  cloud:
    config:
      username: ${SPRING_CLOUD_CONFIG_USERNAME}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD}